name: thebibleapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.02+02

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  google_mobile_ads: ^1.1.0
  get: ^4.6.5
  hive: ^2.2.3
  intl: ^0.17.0
  loading_animations: ^2.2.0
  package_info: ^2.0.2
  path_provider: ^2.0.11
  provider: ^6.0.2
  sqflite: ^2.0.1
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  share: ^2.0.4
  flutter_widget_from_html: ^0.8.5
  webview_flutter: ^3.0.4
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_messaging: ^11.2.6
  firebase_database: ^9.0.6
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  http: ^0.13.4
  shimmer: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_local_notifications: ^9.1.4
  cached_network_image: ^3.2.1
  chewie: ^1.3.4
  video_player: ^2.4.5
  # flutter_geofire: ^2.0.1
  device_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4

#flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/databases/
    - assets/church.mp4
    - assets/prayers.jpg
